//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

#include <iostream>
using namespace std;
int fiboEvenSum(int n){
    int a = 2, b = 3;
    int sum = 0;
    while(a<=n){
        if(a%2==0){
            sum += a;
        }
        int next = a+b;
        a = b;
        b = next;
    }
    return sum;
}
int main(){
    int n;
    cin >> n;
    int result = fiboEvenSum(n);
    cout << result << endl;
}
